### PR TITLE
Compile with ghc 8.6 by pushing MonadFail usage into IO

### LINKED ISSUE #4: Build failure with ghc-8.6
See: https://ghc.haskell.org/trac/ghc/wiki/Migration/8.6#MonadFailDesugaringbydefault

```
[1 of 3] Compiling Yesod.Auth.Facebook.ClientSide ( src/Yesod/Auth/Facebook/ClientSide.hs, dist/build/Yesod/Auth/Facebook/ClientSide.o )

src/Yesod/Auth/Facebook/ClientSide.hs:525:13: error:
    • Could not deduce (Control.Monad.Fail.MonadFail m)
        arising from a do statement
        with the failable pattern ‘Just exptime’
      from the context: YesodAuthFbClientSide site
        bound by the type signature for:
                   getUserAccessTokenFromFbCookie :: forall site.
                                                     YesodAuthFbClientSide site =>
                                                     AuthHandler
                                                       site (Either String FB.UserAccessToken)
        at src/Yesod/Auth/Facebook/ClientSide.hs:(500,1)-(502,53)
      or from: MonadAuthHandler site m
        bound by the type signature for:
                   getUserAccessTokenFromFbCookie :: AuthHandler
                                                       site (Either String FB.UserAccessToken)
        at src/Yesod/Auth/Facebook/ClientSide.hs:(503,1)-(562,29)
      Possible fix:
        add (Control.Monad.Fail.MonadFail m) to the context of
          the type signature for:
            getUserAccessTokenFromFbCookie :: AuthHandler
                                                site (Either String FB.UserAccessToken)
    • In a stmt of a 'do' block:
        Just exptime <- lookupSession sessionExpires
      In the second argument of ‘($)’, namely
        ‘do Just userId <- lookupSession sessionUserId
            Just data_ <- lookupSession sessionToken
            Just exptime <- lookupSession sessionExpires
            return
              $ FB.UserAccessToken
                  (FB.Id userId) data_ (read $ T.unpack exptime)’
      In the expression:
        lift
          $ do Just userId <- lookupSession sessionUserId
               Just data_ <- lookupSession sessionToken
               Just exptime <- lookupSession sessionExpires
               return
                 $ FB.UserAccessToken (FB.Id userId) data_ (read $ T.unpack exptime)
    |
525 |             Just exptime <- lookupSession sessionExpires
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by tolysz**
following the changes from yesod
https://github.com/yesodweb/yesod/commit/132abccff20a406e71aa3079cf67a4655f97539f
fixes https://github.com/psibi/yesod-auth-fb/issues/4

### CODE REVIEW

**Comment by psibi** [comment]
Thanks!

**Comment by psibi** [comment]
Also Released a new version to Hackage including this. Thanks.
